### ISSUE TITLE
Error on usage,  how to use?

### ISSUE THREAD

**Issue by azn1viet** [vilic/cordova-plugin-tts#10]
I have a hard time using this plugin, after install the plugin via cordova plugin add cordova-plugin-tts

Installing "cordova-plugin-tts" for android

In  index.html:

TTS.speak({
                    text: 'Welcome to the app!',
                    locale: 'en-GB',
                    rate: 0.75
                }, function () {
                    alert('success');
                }, function (reason) {
                    alert(reason);
                });
-----------------------------------------------------------------------------

Errors:

Uncaught ReferenceError: exports is not defined tts.js:9

Uncaught ReferenceError: TTS is not defined       index.html:245

**Comment by azn1viet** [comment]
put it in deviceready will work. 
 
    document.addEventListener("deviceready", onDeviceReady, false);
        function onDeviceReady() {

window.TTS.speak({
text: 'Welcome to the app!',
locale: 'en-GB',
rate: 0.75
}, function () {
alert('success');
}, function (reason) {
alert(reason);

});
}

**Comment by prabhatmishra33** [comment]
This Issue should be reopened , facing the same issue

using below dependencies version :
  "dependencies": {
    "cordova-android": "^8.1.0",
    "cordova-browser": "^6.0.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-speechrecognition": "^1.2.0",
    "cordova-plugin-tts": "^0.2.3"
}

edit : I installed the package using npm, later realized it should be installed through
`cordova plugin add cordova-plugin-tts`

It worked after that.
