### ISSUE TITLE
TypeError: onfulfilled is not a function

### ISSUE THREAD

**Issue by ipmanlk** [vilic/cordova-plugin-tts#104]
After calling TTS.speak, Cordova is throwing an error,

`
Error in Success callbackId: TTS753568219 : TypeError: onfulfilled is not a function
cordova.js:307 TypeError: onfulfilled is not a function
    at tts.js:25
    at Object.callbackFromNative (cordova.js:288)
    at <anonymous>:1:9
`

**Comment by NP-Systems** [comment]
same error with ios 5.0.1.
does not work after then()

```
      TTS.speak({
        text: "first",
        locale: 'en-US',
      }).then(() => {
        TTS.speak({
          text: "second",
          locale: 'en-US',
        }).then(() => {
        })
      }).catch((err) => {
      });
```

Any help?
```
Error in Success callbackId: TTS594694329 : TypeError: onfulfilled is not a function. (In 'onfulfilled()', 'onfulfilled' is undefined)
cordova.js:1510 file:///var/containers/Bundle/Application/DEE80112-1946-4C71-A275-85B1234BA0D7/appname.app/www/plugins/cordova-plugin-tts/www/tts.js:25:24
callbackFromNative@file:///var/containers/Bundle/Application/DEE80112-1946-4C71-A275-85B1234BA0D7/appname.app/www/cordova.js:288:63
nc2@file:///var/containers/Bundle/Application/DEE80112-1946-4C71-A275-85B1234BA0D7/appname.app/www/cordova.js:1039:39
```

**Comment by sajdre** [comment]
You can pass onSuccess and onError functions instead of promise style. At least it works.

**Comment by marsiliflavio** [comment]
Hi,
i have the same problem on Cordova version 9.0.1 and this plugins installed:
cordova device plugin 2.0.2
cordova TTS 0.1.1
cordova camerapreview 0.11.2
with this error
Error in Success callbackId: TTS1037081306: TypeError: onfulfilled is not a function. (In 'onfulfilled()', 'onfulfilled' is undefined)
...tts.js:25:24
...cordova.js:1073:39

**Comment by ipmanlk** [comment]
Passing **onSuccess** and **onError** callback functions instead of promise style fixed the issue.
