### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by jnccneto** [vilic/cordova-plugin-tts#11]
Hi
Was trying the example you have but got this error:

Uncaught ReferenceError: TTS is not defined

I just installed the plugin on cordova and tested the example code:

TTS
    .speak('Cordova Plugin SpeechSynthesisUtterance Test', function () {
        alert('success');
    }, function (reason) {
        alert(reason);
    });

Can you provide a more detailed example, do I need to create a new TTS object?

**Comment by vilic** [comment]
Hi, all cordova plugins are not usable until `deviceready` event emits. Please make sure your code is executed after `deviceready` event.

**Comment by jnccneto** [comment]
yep, you're right :-)
my mistake 
thanks

**Comment by vilic** [comment]
;)
