### ISSUE TITLE
witch TTS ? 

### ISSUE THREAD

**Issue by jnccneto** [vilic/cordova-plugin-tts#12]
Hi
Been playing with the plugin and it works fine.
Just would like to know what is the TTS engine it uses?
Is it the browser/webview? or some installed software on device?
I ask to know what is needed to enabled more voices options, if they should be installed by the user.

Also, I haven't managed a way to use punctuation like question mark ( ? ) or exclamation (!) 
Is it supported?

Thanks

**Comment by vilic** [comment]
Hi, it uses the default TTS engine on specific system (not browser level API). Whether the TTS engine would process question mark or exclamation correctly can not be controlled by this plugin.

If you want more options, you may need to change the source code of this plugin.
