### ISSUE TITLE
Cannot read property 'speak' of undefined

### ISSUE THREAD

**Issue by Carlos-Ed-B** [vilic/cordova-plugin-tts#18]
good afternoon
I tried to make the example below

```
                 window.TTS
                   .speak ({
                       text: 'hello world!'
                       locale 'en-GB'
                       rate: 1.1
                   }, Function () {
                   }, Function (reason) {
                   });
```

and I got the following error message

> "Uncaught TypeError: Can not read property 'speak' of undefined"

You could help me in this problem?

Thank you

**Comment by vilic** [comment]
Hi, please make sure you are calling the API after `deviceready` event.
