### ISSUE TITLE
is there any way to stop the voice ?

### ISSUE THREAD

**Issue by bau720123** [vilic/cordova-plugin-tts#2]
hi @vilic 
awesome plugin
work perfect in android , ios, winphone
but it seem there is no "TTS.stop" or  "TTS.pause" method to stop the voice
is it be possible by the future ?

**Comment by vilic** [comment]
you may try speak an empty string so far~

Sent from my Lumia 930
________________________________

**Comment by bau720123** [comment]
hi @vilic 
work perfect !!
thanks
