### ISSUE TITLE
Voice has extremely slow rate on iOS 9+

### ISSUE THREAD

**Issue by LucNaterop** [vilic/cordova-plugin-tts#21]
The default voice is far slower on iOS 9 and than on iOS 8, which is bad, because devs now have to distinguish between the two versions. iOS 8 has still more than 10% market share...
You can increase the rate by using higher values than 1. I figured that the rate that is normal for iOS 8 is obtained for a value of about 1.5. So for iOS 9+ you need to write something like

`TTS.speak({text: 'Watup', rate: 1.5})`

But then again, if this is being executed on iOS 8, it is EXTREMELY fast...

**Comment by KnoxArg** [comment]
Same here, ever fixed it?

**Comment by jwktje** [comment]
I was wondering the same!

**Comment by KnoxArg** [comment]
I found a workaround. I check if the iOS version is 9+ and set the speed to 1.5, if not I leave it with a value of 1.




```
var speed = 1;
		if(window.cordova)
			if(window.device.platform == 'iOS')
				if(window.device.version.charAt(0) == '9')
					speed = 1.5;
					
		
		TTS.speak({
           text: $("#descripcion").html(),
		   rate: speed,
           locale: 'es-AR'
		}, function () {
           // Do Something after success
		}, function (reason) {
           JSON.stringify(reason)
		});	
```

**Comment by DomiR** [comment]
This `// Rate expression adjusted manually for a closer match to other platform.` clearly does not work on iOS 9 any more.
https://github.com/vilic/cordova-plugin-tts/blob/master/src/ios/CDVTTS.m#L67

**Comment by vilic** [comment]
@DomiR Currently I don't have a working iOS device. A PR is welcome.

**Comment by epicfaace** [comment]
It's also really slow when I run it on the iPhone X simulator (iOS 11).

**Comment by srkleiman** [comment]
A rate of 1 is way too slow on my iPhone X and iPad Pro, both running 11.3.
