### ISSUE TITLE
[just a recommand] plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [vilic/cordova-plugin-tts#3]
hi @vilic 

according to these
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by vilic** [comment]
thanks for the information!

**Comment by bau720123** [comment]
it's My pleasure
I will close this topic for now
but if anything progress
please let me know
thanks again

**Comment by vilic** [comment]
:D let's keep this issue open, I will close it after migrations are done.

**Comment by bau720123** [comment]
thanks @vilic again

**Comment by aymanar** [comment]
Any updates regarding this?

**Comment by vilic** [comment]
I think I'll move it to npm if I get some updates or by the date of their closing the registry.

**Comment by bau720123** [comment]
hi @vilic 
just recommanded
I think this is the right time that transfer your plugin to npm
"http://plugins.cordova.io/" for now is totally readonly

**Comment by vilic** [comment]
Thanks for reminding, will do if I get some time. :)

**Comment by bau720123** [comment]
OKOK
thanks @vilic

**Comment by vilic** [comment]
Now it's on npm, finally, `cordova-plugin-tts`.

**Comment by bau720123** [comment]
thanks @vilic
