### ISSUE TITLE
TTS on Android has a maximum character limit

### ISSUE THREAD

**Issue by CookieCookson** [vilic/cordova-plugin-tts#5]
Been getting an unknown error sent through by the Android version of the plugin. I narrowed it down to the fact that the plugin can only support 3999 characters coming through (substring to the rescue!). I have gotten around this by then firing off the next set of characters in the success handler, but you will get an issue where it will mispronounce the word that is split between the two sets.

**Comment by vilic** [comment]
:+1: Thanks for the feedback. Seems to be a known limit with Android 4.x. Maybe you can try to split sentence instead of words. Start from the 3999 character and search back for something like "."?

**Comment by MrShakes** [comment]
I wrote a lil something that may help those with this problem. Note that in my code I accounted for about 4 * 3999 characters which is usually enough for nearly all articles. If you're reading something longer like an ebook then you'll need to modify it.
`document.addEventListener("deviceready", function () {
     var speed = 1;
        TTS.speak({
            text: $scope.article.title,
            rate: speed
        }, function() {
          console.log('success reading title of article');
          var text = $scope.article.text;
          var textLength = $scope.article.text.length;
          if (textLength > 3999) {
            var sub = text.substr(0,3999);
            console.log(text);
            var index = sub.lastIndexOf(".");
            delete $localStorage.index;
            $scope.$storage = $localStorage.$default({
              index: index
            });
            console.log(index);
            var res = text.substr(0,index);
            console.log(res);
            // Read first
            TTS.speak({
                text: res,
                rate: speed
            }, function () {
                console.log('successfully read first');
                  if ($localStorage.index < textLength-1) {
                    var sub = text.substr($localStorage.index,$localStorage.index+3999);
                    var indexx = sub.lastIndexOf(".")
                    console.log(indexx);
                    var res = text.substr($localStorage.index+1,indexx);
                    console.log(res);
                    var whereAmI = $localStorage.index+indexx;
                    console.log(whereAmI);
                    console.log(textLength);
                    delete $localStorage.index;
                    $scope.$storage = $localStorage.$default({
                      index: whereAmI
                    });
                    TTS.speak({
                        text: res,
                        rate: speed
                    }, function () {
                        console.log('successfully read second');
                        if ($localStorage.index < textLength-2) {
                          var sub = text.substr($localStorage.index,$localStorage.index+3999);
                          var indexx = sub.lastIndexOf(".")
                          console.log(indexx);
                          var res = text.substr($localStorage.index+1,indexx);
                          console.log(res);
                          var whereAmI = $localStorage.index+indexx;
                          console.log(whereAmI);
                          console.log(textLength);
                          delete $localStorage.index;
                          $scope.$storage = $localStorage.$default({
                            index: whereAmI
                          });
                          TTS.speak({
                              text: res,
                              rate: speed
                          }, function () {
                              console.log('successfully read third');
                              var res = text.substr($localStorage.index+1, textLength);
                              TTS.speak({
                                  text: res,
                                  rate: speed
                              }, function () {
                                  console.log('successfully read fourth');
                              }, function (reason) {
                                  console.log(reason);
                              });
                          }, function (reason) {
                              console.log(reason);
                          });
                        };
                    }, function (reason) {
                        console.log(reason);
                    });
                  };
            }, function (reason) {
                console.log(reason);
            });
          } else {
            TTS.speak({
                text: text,
                rate: speed
            }, function () {
                console.log('successfully read short article');
            }, function (reason) {
                console.log(reason);
            });
          };
        }, function(reason) {
            console.log(reason);
        });
      }, false);`

**Comment by amitpatil321** [comment]
@MrShakes : Thanks it helped me.
