### ISSUE TITLE
ERR_UNKNOWN on Android

### ISSUE THREAD

**Issue by foaudkajj** [vilic/cordova-plugin-tts#50]
I spent my all two days solving this problem and it was a very very trivial problem.
I opened this issue to make everyone notice this problem and get around it quickly without wasting time.

The solution is to change the Accessibility Text to Speech settings in the phone and make it use Google Text to Speech instead of Samsung Text to Speech ( in my case ).

**Comment by UlisesCeca** [comment]
I did this and I'm still having this issue.
