### ISSUE TITLE
TTS not working on Windows/WP81

### ISSUE THREAD

**Issue by bownie** [vilic/cordova-plugin-tts#6]
Hi there,

I'm trying to get the plugin to work on WP8.1 - building via ionic/cordova with VS2015. Build path is slightly convoluted using 'cordova build windows'  and then selecting the Phone solution from the output provides a fully functioning WP8.1 app apart from this plugin.

The plugin is giving me only - Missing Command Error - on the console.  I've also just build a HelloWorld project with only this plugin in it and same result.  Any clues?

Thanks

**Comment by vilic** [comment]
Have tried `cordova build wp8` instead of `cordova build windows`?

**Comment by bownie** [comment]
Yes I've tried the wp8 build but this doesn't play nicely either - running emulator via command line fails ("cordova emulate wp8") and opening up the resulting project in VS2015 and trying to deploy fails on build.  Think this might be a WP8 vs WP81 thing.  The 'windows' build loads both into emulator and on phone fine but just this plugin not working.

What config do you run/recommend or any tips and tricks on how to debug further?

**Comment by vilic** [comment]
This plugin does not support targeting `windows`, just `wp8`. Are you missing the installation of some SDK or emulator?

**Comment by bownie** [comment]
Ah ok, great. Yes I've now got it working on WP8 but it still looks like my build path is a bit borked.  Thanks for the quick response

**Comment by vilic** [comment]
:smile:
