### ISSUE TITLE
IOS - UI Locks if I change variables in .then() function

### ISSUE THREAD

**Issue by joshglazer** [vilic/cordova-plugin-tts#63]
If I change any variables inside of the .then() function after calling a .speak(), the UI stops updating when I change variables. I have included an example of the code I am running below.  After the TTS speaks the message, the console shows my debugging message, but everything on the screen locks up, even though variables change.  If I don't change any variables in the then() function, I don't seem to have this issue.  After the issue occurs, if I interact with a button on the screen, everything seems to unlock again.

I noticed this error in the logs, right before my debug, but I'm not sure if it's related:
[TTS] TTSPlaybackCreate unable to initialize dynamics: -3000

Has anyone else had an issue like this?  Is there a way to fix this?

Here is the code example:
```
this.paused = true;
this.tts.speak("Try Again")
    .then(() => {
        console.log('finished speaking');
        this.paused = false;
        return true;
    })
```

**Comment by vilic** [comment]
Are you using Angular?

**Comment by joshglazer** [comment]
Yes, I’m using the ionic framework, which uses angular

**Comment by vilic** [comment]
@joshglazer I guess the reason behind this is that zone.js cannot detect asynchronous code originated by Cordova plugin. You may try to trigger that manually.

E.g. inject `zone: NgZone` and `zone.run(() => { })`.

**Comment by joshglazer** [comment]
That worked!  Thanks for the help, I really appreciate it!
