### ISSUE TITLE
onfulfilled is not a function

### ISSUE THREAD

**Issue by beevelop** [vilic/cordova-plugin-tts#73]
| comp | version |
| ----- | ----- |
| Cordova | `v8.0.0` |
| Cordova-iOS | `v4.5.4` |
| Plugin-TTS | `v0.2.3` |

```
onfulfilled is not a function. (In 'onfulfilled()', 'onfulfilled' is undefined)
```

This bug seems to be already fixed in the current `master` branch, but not yet released to npm.

**Comment by PragmaticEd** [comment]
Why haven't this been updated yet?

**Comment by ghost** [comment]
I also got this error. May I ask when it can be updated ? 
Thanks to the author!

**Comment by kickergold** [comment]
Still an issue, would like a fix on NPM if possible.

**Comment by kickergold** [comment]
I've created a new npm package that's got the up-to-date version, if it's useful to anyone but me.
https://www.npmjs.com/package/cordova-plugin-speechrecognition-updated
