### ISSUE TITLE
en-US sounds like a robot

### ISSUE THREAD

**Issue by draganstojanov** [vilic/cordova-plugin-tts#85]
After an update on ios 12 iPhone 5s, en-US is not a female voice. Now it sounds like a robot. Is somebody having the same issue and how to fix it?

**Comment by caleb87** [comment]
Same issue on the iPhone X with iOS 12, but iPhone 6s with iOS 12 does not have the issue. No idea how to fix it currently.

**Comment by caleb87** [comment]
I bought a new iPhone X, the same exact model that had the issue, and updated it to iOS 12 which is the same version the old phone has. The new phone did not have the issue. 

The old phone had "Siri Female" selected under  Settings > General > Accessibility > VoiceOver > Speech > En

But the new phone had "Samantha" selected. My iPhone 6s also had Samantha selected.

After changing the old iPhone X to Samantha, it went away.

Not really a solution, but it could work for customers in a pinch.
