### ISSUE TITLE
android seems to ignore locale

### ISSUE THREAD

**Issue by diego-vieira** [vilic/cordova-plugin-tts#9]
The plugin is working just fine, but I have set the locale to be 'en-GB' and the TTS is using my mobile language which is pt-BR, is there any reason for this?

Using android 5.1.

Thank you

**Comment by vilic** [comment]
Does your phone have en-GB related resources installed?

**Comment by diego-vieira** [comment]
I don't think so, I didn't even know that I had to do that.
Anyway, think I'll go with a different solution as I would like the user to pick up the language.

Great job with the plugin tho.

**Comment by albertytau** [comment]
Try en-UK, it works for me in Android
For IOS, simply en can work
